### ISSUE TITLE
theia-ide: python is not a valid runtime error while deploying

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [okteto/charts#111]
## Steps to Reproduce

1. Create a new deployment using Theia IDE.
2. When YAML editor is on the screen, change the value of `runtime` into `python`.
3. Configure the rest as usual.
4. Hit depkoy.

## Logs

```
Error: template: theia/templates/_helpers.tpl:77:8: executing "theia.image" at <fail (printf "%s is not a valid runtime. Valid values are: %s" .Values.runtime $runtimes)>: error calling fail: python is not a valid runtime. Valid values are: [nodejs go php dart cpp java rust]
```

## My config

```yaml
# available runtimes: go, python, dart, cpp, java, rust, nodejs
runtime: python

# use this to clone a public repository automatically
repository: https://github.com/Community-Lores/community-lores.github.io

# set this when using a private repository https://github.com/settings/tokens
# or add a GIT_TOKEN okteto secret
gitToken:

persistence:
  size: 2Gi

resources:
  limits:
    cpu: "2"
    memory: 6Gi

# This is the port that Theia is running on. Change this if you want to use this port instead
service:
  port: 3000 # Default Theia port
```
